extends Node

enum PlayerId {
	PlayerId_Player,
	PlayerId_Opponent,
}

enum CardZone {
	CardZone_PlayerHand,
	CardZone_PlayerGauge,
	CardZone_PlayerBoosts,
	CardZone_OpponentHand,
	CardZone_OpponentGauge,
	CardZone_OpponentBoosts,
}

enum DecisionType {
	DecisionType_BoostCancel,
	DecisionType_ChooseDiscardContinuousBoost,
	DecisionType_EffectChoice,
	DecisionType_NameCard_OpponentDiscards,
	DecisionType_PayStrikeCost_Required,
	DecisionType_PayStrikeCost_CanWild,
	DecisionType_ForceForArmor,
	DecisionType_CardFromHandToGauge,
	DecisionType_StrikeNow,
}

enum GameState {
	GameState_NotStarted,
	GameState_Boost_Processing,
	GameState_GameOver,
	GameState_PickAction,
	GameState_DiscardDownToMax,
	GameState_Mulligan,
	GameState_WaitForStrike,
	GameState_PlayerDecision,
	GameState_Strike_Opponent_Response,
	GameState_Strike_Processing,
}

enum EventType {
	EventType_AddToGauge,
	EventType_AddToDiscard,
	EventType_AddToDeck,
	EventType_AdvanceTurn,
	EventType_Boost_ActionAfterBoost,
	EventType_Boost_CancelDecision,
	EventType_Boost_DiscardContinuousChoice,
	EventType_Boost_Played,
	EventType_Boost_Canceled,
	EventType_Boost_Continuous_Added,
	EventType_Boost_NameCardOpponentDiscards,
	EventType_CardFromHandToGauge_Choice,
	EventType_ChangeCards,
	EventType_Discard,
	EventType_Draw,
	EventType_Exceed,
	EventType_ForceStartStrike,
	EventType_GameOver,
	EventType_HandSizeExceeded,
	EventType_Move,
	EventType_MulliganDecision,
	EventType_Prepare,
	EventType_ReshuffleDeck_Mulligan,
	EventType_ReshuffleDiscard,
	EventType_RevealHand,
	EventType_Strike_ArmorUp,
	EventType_Strike_CardActivation,
	EventType_Strike_DodgeAttacks,
	EventType_Strike_EffectChoice,
	EventType_Strike_ExUp,
	EventType_Strike_ForceForArmor,
	EventType_Strike_ForceWildSwing,
	EventType_Strike_GainAdvantage,
	EventType_Strike_GuardUp,
	EventType_Strike_IgnoredPushPull,
	EventType_Strike_Miss,
	EventType_Strike_PayCost_Gauge,
	EventType_Strike_PayCost_Force,
	EventType_Strike_PayCost_Unable,
	EventType_Strike_PowerUp,
	EventType_Strike_RangeUp,
	EventType_Strike_Response,
	EventType_Strike_Response_Ex,
	EventType_Strike_Reveal,
	EventType_Strike_SpeedUp,
	EventType_Strike_Started,
	EventType_Strike_Started_Ex,
	EventType_Strike_Stun,
	EventType_Strike_TookDamage,
	EventType_Strike_WildStrike,
}
